delete_merged_branches = true
update_base_for_deletes = true

timeout-sec = 7200 # two hours, in seconds

status = [
	'bors-ok',
]
pr_status = [
	'linear-history',
	'CI / Lint / Lint GHA',
	'CI / Lint / Lint Go',
	'CI / Lint / Lint Protobufs',
	'CI / Lint / Lint SDKs',
]
